spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot_sandbox
      username: root
      password: example
      authentication-database: admin

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: springboot-sandbox
