apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: springboot-sandbox
data:
  SPRING_DATA_MONGODB_URI: "mongodb://root:example@mongodb:27017/springboot_sandbox?authSource=admin"
  SERVER_PORT: "8080"
