resources:
- ../../base

patches:
- target:
    kind: ConfigMap
    name: app-config
  path: configmap-patch.yaml
- target:
    kind: Deployment
    name: springboot-sandbox
  path: monitoring-patch.yaml
