name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: springboot-sandbox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build and Test
      run: mvn clean verify

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy-staging:
    needs: build-docker
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Staging
      run: kubectl apply -k k8s/overlays/staging
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_STAGING }}

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # Only deploy to prod on version tags (v1.0.0)
    steps:
    - uses: actions/checkout@v4
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Production
      run: |
        kubectl apply -k k8s/overlays/prod
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PROD }}
        MONGO_PROD_PASSWORD: ${{ secrets.MONGO_PROD_PASSWORD }}
